### ISSUE TITLE
Yahoo accounts don't allow log in when you reinstall the app

### ISSUE THREAD

**Issue by Unwrap-at** [mustang-im/mustang#180] opened 2024-08-16 16:27 UTC
I download Mustang 0.6.0
I go to mail
Google accounts ask for the log in with a sign in window (when I click on the log in icon)
My hetzner and Yahoo accounts stay with the '?' on the icon and error message saying : Check your login, and password. Unexpected close.
![Screenshot (458)](https://github.com/user-attachments/assets/9da5de4f-3cab-486a-8a51-f1aaeb485974)

![Screenshot (460)](https://github.com/user-attachments/assets/6e245a28-6946-4ab7-95b1-3f89cd36c4fb)
![Screenshot (459)](https://github.com/user-attachments/assets/c517b40b-98ca-4feb-8b38-d638743326b6)

**Comment by benbucksch** [comment] 2024-08-20 11:58
@jermy-c Is that fixed by #182, or is this a different bug?

**Comment by jermy-c** [comment] 2024-08-20 16:08
No, it seems to be a different bug. #182 fixes `Error: Missing code verifier`. I was trying to reproduce this bug but got the `Error: Missing code verifier` bug.

**Comment by jermy-c** [comment] 2024-08-23 16:41
While testing:

- an error message appears: 'no such column: tagName'
- the exact error in this didn't appear

Solution:

- Delete the data folder in `%APPDATA%`

Possible cause:

- it was still trying to do PKCE for the refresh token
- old data structure, possibly because before the refresh tokens were saved plainly and now they are saved as password salts. And maybe the Yahoo logins weren't updated and were using the old structures and the code submitted something different as the refresh token.

**Closed by jermy-c** 2024-08-23 16:41 UTC
